server:
  port: ${SERVER_PORT_ORDER:8050}
  servlet:
    context-path: /api/v1/orders
    encoding:
      charset: UTF-8

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
  api-docs:
    path: /docs

spring:
  messages:
    encoding: UTF-8
    basename: messages/api_error_messages, messages/db_error_messages
  application:
    name: order
  datasource:
    url: ${DATASOURCE_URL_ORDER:jdbc:postgresql://localhost:5432/bestclick}
    username: ${DATASOURCE_USERNAME_ORDER:bestclick}
    password: ${DATASOURCE_PASSWORD_ORDER:R0stov2000}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${MAX_POOL_SIZE:3}
  liquibase:
    enabled: false
  beaninfo:
    ignore: false

management:
  endpoint:
    health:
      enabled: true
      show-details: always
      cache.time-to-live: 100ms
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure.include: health, info

bestclick:
  logging:
    exception:
      business: ${LOGGING_BUSINESS_EX:true}
      server: ${LOGGING_SERVER_EX:true}

logging:
  level:
    ru: ${LOGGING_WEB:DEBUG}
    org:
      springframework:
        web: ${LOGGING_WEB:INFO}
      jooq: ${LOGGING_JOOQ:INFO}